const geography = [
    'andes mountains', 'amazon river', 'appalachian mountains', 'alps', 'arctic ocean',
    'atlantic ocean', 'amazon basin', 'arabian peninsula', 'archipelago', 'atoll',
    'africa', 'asia', 'antarctica', 'australia', 'austria', 'argentina', 'algeria',
    'afghanistan', 'albania', 'angola', 'azerbaijan', 'bangladesh', 'brazil', 'bolivia',
    'botswana', 'belgium', 'bulgaria', 'bahamas', 'belize', 'bhutan', 'burma', 'brunei',
    'cambodia', 'canada', 'chile', 'china', 'colombia', 'congo', 'costa rica', 'croatia',
    'cuba', 'cyprus', 'czechia', 'denmark', 'dominican republic', 'ecuador', 'egypt',
    'el salvador', 'estonia', 'ethiopia', 'fiji', 'finland', 'france', 'gabon', 'germany',
    'ghana', 'greece', 'greenland', 'guatemala', 'guinea', 'haiti', 'honduras', 'hungary',
    'iceland', 'india', 'indonesia', 'iran', 'iraq', 'ireland', 'israel', 'italy',
    'jamaica', 'japan', 'jordan', 'kazakhstan', 'kenya', 'kuwait', 'laos', 'latvia',
    'lebanon', 'liberia', 'libya', 'lithuania', 'madagascar', 'malaysia', 'mali', 'malta',
    'mexico', 'mongolia', 'morocco', 'mozambique', 'myanmar', 'namibia', 'nepal',
    'netherlands', 'new zealand', 'nicaragua', 'niger', 'nigeria', 'north korea', 'norway',
    'oman', 'pakistan', 'panama', 'paraguay', 'peru', 'philippines', 'poland', 'portugal',
    'qatar', 'romania', 'russia', 'rwanda', 'saudi arabia', 'senegal', 'serbia',
    'singapore', 'slovakia', 'slovenia', 'somalia', 'south africa', 'south korea', 'spain',
    'sri lanka', 'sudan', 'sweden', 'switzerland', 'syria', 'taiwan', 'tanzania',
    'thailand', 'tunisia', 'turkey', 'uganda', 'ukraine', 'united arab emirates',
    'united kingdom', 'united states', 'uruguay', 'uzbekistan', 'venezuela', 'vietnam',
    'yemen', 'zambia', 'zimbabwe', 'pacific ocean', 'indian ocean', 'southern ocean',
    'mediterranean sea', 'caribbean sea', 'south china sea', 'bering sea', 'gulf of mexico',
    'hudson bay', 'persian gulf', 'red sea', 'black sea', 'caspian sea', 'dead sea',
    'baltic sea', 'north sea', 'coral sea', 'tasman sea', 'bay of bengal', 'arabian sea',
    'nile river', 'mississippi river', 'yangtze river', 'ganges river', 'mekong river',
    'danube river', 'rhine river', 'volga river', 'congo river', 'niger river',
    'zambezi river', 'colorado river', 'rio grande', 'euphrates river', 'tigris river',
    'indus river', 'ob river', 'yenisei river', 'lena river', 'mackenzie river',
    'missouri river', 'ohio river', 'columbia river', 'yukon river', 'orinoco river',
    'parana river', 'murray river', 'huang he river', 'seine river', 'thames river',
    'po river', 'elbe river', 'oder river', 'dnieper river', 'don river', 'ural river',
    'mount everest', 'mount kilimanjaro', 'mount mckinley', 'mount fuji', 'mount vesuvius',
    'mount etna', 'mount rainier', 'mount whitney', 'matterhorn', 'mont blanc',
    'mount olympus', 'mount kenya', 'mount elbrus', 'himalayas', 'rocky mountains',
    'sierra nevada', 'cascade range', 'great dividing range', 'ural mountains', 'pyrenees',
    'carpathian mountains', 'caucasus mountains', 'hindu kush', 'karakoram',
    'atlas mountains', 'drakensberg mountains', 'tian shan', 'kunlun mountains',
    'altai mountains', 'brooks range', 'alaska range', 'coast range', 'blue ridge mountains',
    'ozark mountains', 'black hills', 'adirondack mountains', 'white mountains',
    'green mountains', 'sahara desert', 'gobi desert', 'kalahari desert', 'arabian desert',
    'mojave desert', 'sonoran desert', 'atacama desert', 'patagonian desert',
    'great victoria desert', 'simpson desert', 'namib desert', 'thar desert',
    'taklamakan desert', 'karakum desert', 'great basin desert', 'chihuahuan desert',
    'colorado plateau', 'tibetan plateau', 'deccan plateau', 'brazilian highlands',
    'ethiopian highlands', 'mexican plateau', 'columbia plateau', 'ozark plateau',
    'great plains', 'coastal plain', 'pampas', 'steppes', 'savanna', 'tundra', 'taiga',
    'rainforest', 'deciduous forest', 'grassland', 'wetland', 'marsh', 'swamp', 'bog',
    'delta', 'estuary', 'fjord', 'peninsula', 'isthmus', 'strait', 'channel', 'cape',
    'bay', 'gulf', 'lagoon', 'reef', 'barrier island', 'volcano', 'crater', 'caldera',
    'geyser', 'hot spring', 'glacier', 'iceberg', 'ice sheet', 'permafrost', 'moraine',
    'valley', 'canyon', 'gorge', 'ravine', 'basin', 'plateau', 'mesa', 'butte', 'hill',
    'ridge', 'peak', 'summit', 'cliff', 'escarpment', 'fault line', 'continental shelf',
    'continental slope', 'ocean trench', 'mid-ocean ridge', 'abyssal plain', 'seamount',
    'island chain', 'coral reef', 'great barrier reef', 'grand canyon', 'victoria falls',
    'niagara falls', 'angel falls', 'iguazu falls', 'great lakes', 'lake superior',
    'lake michigan', 'lake huron', 'lake erie', 'lake ontario', 'lake victoria',
    'lake tanganyika', 'lake baikal', 'lake titicaca', 'lake chad', 'lake malawi',
    'aral sea', 'great salt lake', 'lake tahoe', 'crater lake', 'lake geneva', 'lake como',
    'loch ness', 'great rift valley', 'death valley', 'silicon valley', 'central valley',
    'fertile crescent', 'indus valley', 'nile delta', 'ganges delta', 'mekong delta',
    'mississippi delta', 'okavango delta', 'panama canal', 'suez canal', 'erie canal',
    'english channel', 'strait of gibraltar', 'strait of magellan', 'bering strait',
    'strait of hormuz', 'bosporus strait', 'dardanelles', 'drake passage', 'cape horn',
    'cape of good hope', 'cape cod', 'florida keys', 'hawaiian islands', 'galapagos islands',
    'caribbean islands', 'polynesia', 'melanesia', 'micronesia', 'british isles',
    'japanese archipelago', 'indonesian archipelago', 'philippine archipelago',
    'aleutian islands', 'mariana trench', 'puerto rico trench', 'java trench',
    'ring of fire', 'san andreas fault', 'great wall of china', 'machu picchu',
    'stonehenge', 'pyramids of giza', 'colosseum', 'taj mahal', 'angkor wat', 'petra',
    'acropolis', 'parthenon', 'eiffel tower', 'statue of liberty', 'sydney opera house',
    'golden gate bridge', 'empire state building', 'big ben', 'brandenburg gate',
    'kremlin', 'vatican city', 'westminster abbey', 'notre dame cathedral', 'longitude',
    'latitude', 'equator', 'prime meridian', 'tropic of cancer', 'tropic of capricorn',
    'arctic circle', 'antarctic circle', 'international date line', 'time zone',
    'hemisphere', 'north pole', 'south pole', 'continent', 'subcontinent', 'region',
    'territory', 'province', 'state', 'county', 'district', 'municipality', 'capital city',
    'metropolitan area', 'urban area', 'suburban area', 'rural area', 'population density',
    'climate zone', 'temperate zone', 'tropical zone', 'polar zone', 'monsoon',
    'trade winds', 'westerlies', 'jet stream', 'ocean current', 'gulf stream', 'el nino',
    'la nina', 'tsunami', 'earthquake', 'volcanic eruption', 'hurricane', 'typhoon',
    'cyclone', 'tornado', 'flood', 'drought', 'erosion', 'weathering', 'deposition',
    'sedimentation', 'topography', 'elevation', 'sea level', 'contour line', 'relief map',
    'physical map', 'political map', 'thematic map', 'cartography', 'scale', 'legend',
    'compass rose', 'grid system', 'coordinates', 'gps', 'remote sensing', 'gis',
    'satellite imagery', 'aerial photography', 'natural resource', 'renewable resource',
    'nonrenewable resource', 'fossil fuel', 'mineral deposit', 'aquifer', 'watershed',
    'drainage basin', 'tributary', 'source', 'mouth', 'floodplain', 'levee', 'dam',
    'reservoir', 'irrigation', 'aqueduct', 'desalination', 'deforestation', 'reforestation',
    'conservation', 'biodiversity', 'ecosystem', 'habitat', 'biome', 'endangered species',
    'national park', 'wildlife reserve', 'world heritage site', 'yellowstone', 'yosemite',
    'serengeti', 'amazon rainforest', 'congo rainforest', 'borneo rainforest', 'siberia',
    'outback', 'patagonia', 'scandinavia', 'balkans', 'iberian peninsula',
    'italian peninsula', 'korean peninsula', 'indochina', 'horn of africa', 'maghreb',
    'sahel', 'sub-saharan africa', 'middle east', 'central asia', 'southeast asia',
    'east asia', 'south asia', 'oceania', 'latin america', 'central america',
    'north america', 'south america', 'western europe', 'eastern europe', 'northern europe',
    'southern europe', 'european union', 'commonwealth', 'nato', 'united nations',
    'berlin', 'paris', 'london', 'rome', 'madrid', 'vienna', 'prague', 'warsaw', 'moscow',
    'beijing', 'tokyo', 'seoul', 'bangkok', 'singapore', 'sydney', 'melbourne', 'cairo',
    'cape town', 'nairobi', 'lagos', 'mumbai', 'delhi', 'shanghai', 'hong kong', 'dubai',
    'istanbul', 'athens', 'amsterdam', 'brussels', 'geneva', 'zurich', 'stockholm', 'oslo',
    'copenhagen', 'helsinki', 'reykjavik', 'dublin', 'edinburgh', 'lisbon', 'barcelona',
    'milan', 'venice', 'florence', 'munich', 'frankfurt', 'cologne', 'hamburg', 'krakow',
    'budapest', 'bucharest', 'sofia', 'belgrade', 'zagreb', 'ljubljana', 'bratislava',
    'minsk', 'kyiv', 'tbilisi', 'baku', 'yerevan', 'tehran', 'baghdad', 'damascus',
    'beirut', 'amman', 'jerusalem', 'tel aviv', 'riyadh', 'doha', 'abu dhabi', 'muscat',
    'karachi', 'lahore', 'dhaka', 'kolkata', 'chennai', 'bangalore', 'hyderabad', 'osaka',
    'kyoto', 'taipei', 'manila', 'jakarta', 'kuala lumpur', 'ho chi minh city', 'hanoi',
    'yangon', 'phnom penh', 'vientiane', 'auckland', 'wellington', 'perth', 'brisbane',
    'vancouver', 'toronto', 'montreal', 'ottawa', 'chicago', 'los angeles', 'new york',
    'houston', 'phoenix', 'philadelphia', 'san antonio', 'san diego', 'dallas', 'san jose',
    'austin', 'san francisco', 'seattle', 'denver', 'boston', 'atlanta', 'miami',
    'washington dc', 'detroit', 'minneapolis', 'portland', 'las vegas', 'new orleans',
    'honolulu', 'anchorage', 'mexico city', 'guadalajara', 'monterrey', 'havana',
    'kingston', 'san juan', 'guatemala city', 'san salvador', 'tegucigalpa', 'managua',
    'panama city', 'bogota', 'caracas', 'quito', 'lima', 'la paz', 'santiago',
    'buenos aires', 'montevideo', 'asuncion', 'brasilia', 'rio de janeiro', 'sao paulo',
    'salvador', 'manaus'
];
